### PR TITLE
fix for primary keys upper case

### PR DESCRIPTION
**Pull request by jmriego**
Hi! sending a pull request to fix an issue when the primary keys of the source tables are in uppercase. Related to this issue:
https://github.com/jmriego/pipelinewise-target-bigquery/issues/3

### CODE REVIEW

**Comment by jmriego** [comment]
Hi @koszti ,

Just a quick question about this. How do the other Pipelinewise taps behave related to the case of the column names?

Do they keep the case of the source database or save the column names in uppercase? Can you have two column names that differ only in case (let's say `id` and `ID`)?

**Comment by koszti** [comment]
hey, the column and target names are **not** case sensitive in the targets and cannot have two columns that differ only in case. so ID, Id, id all should create the same column.

Can you please make sure following this approach so every target will behave the same?

Related code in target-snowflake at https://github.com/transferwise/pipelinewise-target-snowflake/blob/35e95e7dae6e3c6be28e298f697cb52a85c39064/target_snowflake/db_sync.py#L93

**Comment by jmriego** [comment]
yes, that's fine. I had them as lowercase instead but I can make them uppercase as well if that's needed
https://github.com/transferwise/pipelinewise-target-bigquery/blob/5e741f7fbbf66cf0669e4a999726fe531dd9e25b/target_bigquery/db_sync.py#L152

**Comment by koszti** [comment]
thanks, how does BigQuery handing case sensitive, but not quoted table and column names?
Will all these SQLs work without using quotes?
```
SELECT my_column FROM my_table;
SELECT MY_COLUMN FROM MY_TABLE;
SELECT My_Column FROM My_Table;
```

**Comment by jmriego** [comment]
in BigQuery the table names are case sensitive but the column names are not. Let's say we have this table:
image
This query works:
```
select
    id as a, ID as b,
    _sdc_extracted_at as c, _SDC_EXTRACTED_AT as d
from `dip-sandbox-coresvcs-4578`.raw.tbladcusers_accounts
```
But `select * from `dip-sandbox-coresvcs-4578`.raw.TBLADCUSERS_ACCOUNTS` would fail

**Comment by jmriego** [comment]
in BigQuery the table names are case sensitive but the column names are not. Let's say we have this table:
image
image

This query works:
```
select
    id as a, ID as b,
    _sdc_extracted_at as c, _SDC_EXTRACTED_AT as d
from raw.tbladcusers_accounts
```

But `select * from raw.TBLADCUSERS_ACCOUNTS` would fail

**Review by koszti — APPROVED** [review]

**Pull request merged**
