### PR TITLE
Repeated records

### PR DESCRIPTION
**Pull request by edgarrmondragon**
## Problem

Allow `REPEATED` fields of type `RECORD` to be created.

## Proposed changes

Right now JSON arrays with items of type `object` are being stored as `REPATED` columns of type `string`.

## Types of changes

What types of changes does your code introduce to target-bigquery?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Description above provides context of the change
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Unit tests for changes (not needed for documentation changes)
- [x] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by edgarrmondragon** [comment]
Hello! I've implemented column types for `repeated` records and addressed TODOs in the unit tests for those. Let me know if this looks good 😄

**Comment by edgarrmondragon** [comment]
Hi @Samira-El! Any chance of reviewing this? 😸

**Comment by jmriego** [comment]
hi @edgarrmondragon ! I'm the original developer of this target that then TransferWise merged. I can't remember the details for why I didn't develop it this way in the first place but I think there are some tests you'd still have to do to be safe:
1. Add a test that checks what happens if one of these object json arrays change the object type. Will that fail? Create a new column with a different structure of the record?
2. Add end to end tests that include data for these records. At the moment you only are testing the mapping but not the data insertion

Thanks!

**Comment by edgarrmondragon** [comment]
@jmriego Hey, thanks for the suggestions! I added an integration test and actually caught a bug I had left alive for repeated unstructured records (i.e. missing or empty `properties`).

Those tests are passing

```console
$ make integration_test
. ./venv/bin/activate ;\
        pytest tests/integration --cov=target_bigquery -v
=========================================================================================================== test session starts =======================================
platform darwin -- Python 3.7.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/edgarramirez/Code/pipelinewise-target-bigquery/venv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/edgarramirez/Code/pipelinewise-target-bigquery
plugins: cov-3.0.0
collected 22 items

tests/integration/test_target_bigquery.py::TestIntegration::test_column_name_change PASSED                                                                       [  4%]
tests/integration/test_target_bigquery.py::TestIntegration::test_decimal_number_range PASSED                                                                     [  9%]
tests/integration/test_target_bigquery.py::TestIntegration::test_flush_streams_with_intermediate_flushes PASSED                                                  [ 13%]
tests/integration/test_target_bigquery.py::TestIntegration::test_flush_streams_with_intermediate_flushes_on_all_streams PASSED                                   [ 18%]
tests/integration/test_target_bigquery.py::TestIntegration::test_flush_streams_with_no_intermediate_flushes PASSED                                               [ 22%]
tests/integration/test_target_bigquery.py::TestIntegration::test_invalid_json PASSED                                                                             [ 27%]
tests/integration/test_target_bigquery.py::TestIntegration::test_loading_tables_with_client_side_encryption PASSED                                               [ 31%]
tests/integration/test_target_bigquery.py::TestIntegration::test_loading_tables_with_defined_parallelism PASSED                                                  [ 36%]
tests/integration/test_target_bigquery.py::TestIntegration::test_loading_tables_with_hard_delete PASSED                                                          [ 40%]
tests/integration/test_target_bigquery.py::TestIntegration::test_loading_tables_with_metadata_columns PASSED                                                     [ 45%]
tests/integration/test_target_bigquery.py::TestIntegration::test_loading_tables_with_no_encryption PASSED                                                        [ 50%]
tests/integration/test_target_bigquery.py::TestIntegration::test_loading_unicode_characters PASSED                                                               [ 54%]
tests/integration/test_target_bigquery.py::TestIntegration::test_loading_with_multiple_schema PASSED                                                             [ 59%]
tests/integration/test_target_bigquery.py::TestIntegration::test_logical_streams_from_pg_with_hard_delete_and_batch_size_of_5_and_no_records_should_pass PASSED  [ 63%]
tests/integration/test_target_bigquery.py::TestIntegration::test_logical_streams_from_pg_with_hard_delete_and_batch_size_of_5_should_pass PASSED                 [ 68%]
tests/integration/test_target_bigquery.py::TestIntegration::test_logical_streams_from_pg_with_hard_delete_and_default_batch_size_should_pass PASSED              [ 72%]
tests/integration/test_target_bigquery.py::TestIntegration::test_message_order PASSED                                                                            [ 77%]
tests/integration/test_target_bigquery.py::TestIntegration::test_nested_schema_flattening PASSED                                                                 [ 81%]
tests/integration/test_target_bigquery.py::TestIntegration::test_nested_schema_unflattening PASSED                                                               [ 86%]
tests/integration/test_target_bigquery.py::TestIntegration::test_non_db_friendly_columns PASSED                                                                  [ 90%]
tests/integration/test_target_bigquery.py::TestIntegration::test_repeated_records PASSED                                                                         [ 95%]
tests/integration/test_target_bigquery.py::TestIntegration::test_reserved_word_table_name PASSED                                                                 [100%]
```

**Comment by NiallRees** [comment]
> @jmriego Hey, thanks for the suggestions! I added an integration test and actually caught a bug I had left alive for repeated unstructured records (i.e. missing or empty `properties`).
> 
> Those tests are passing
> 
> ```
> $ make integration_test
> . ./venv/bin/activate ;\
>         pytest tests/integration --cov=target_bigquery -v
> =========================================================================================================== test session starts =======================================
> platform darwin -- Python 3.7.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /Users/edgarramirez/Code/pipelinewise-target-bigquery/venv/bin/python3
> cachedir: .pytest_cache
> rootdir: /Users/edgarramirez/Code/pipelinewise-target-bigquery
> plugins: cov-3.0.0
> collected 22 items
> 
> tests/integration/test_target_bigquery.py::TestIntegration::test_column_name_change PASSED                                                                       [  4%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_decimal_number_range PASSED                                                                     [  9%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_flush_streams_with_intermediate_flushes PASSED                                                  [ 13%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_flush_streams_with_intermediate_flushes_on_all_streams PASSED                                   [ 18%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_flush_streams_with_no_intermediate_flushes PASSED                                               [ 22%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_invalid_json PASSED                                                                             [ 27%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_loading_tables_with_client_side_encryption PASSED                                               [ 31%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_loading_tables_with_defined_parallelism PASSED                                                  [ 36%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_loading_tables_with_hard_delete PASSED                                                          [ 40%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_loading_tables_with_metadata_columns PASSED                                                     [ 45%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_loading_tables_with_no_encryption PASSED                                                        [ 50%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_loading_unicode_characters PASSED                                                               [ 54%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_loading_with_multiple_schema PASSED                                                             [ 59%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_logical_streams_from_pg_with_hard_delete_and_batch_size_of_5_and_no_records_should_pass PASSED  [ 63%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_logical_streams_from_pg_with_hard_delete_and_batch_size_of_5_should_pass PASSED                 [ 68%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_logical_streams_from_pg_with_hard_delete_and_default_batch_size_should_pass PASSED              [ 72%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_message_order PASSED                                                                            [ 77%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_nested_schema_flattening PASSED                                                                 [ 81%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_nested_schema_unflattening PASSED                                                               [ 86%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_non_db_friendly_columns PASSED                                                                  [ 90%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_repeated_records PASSED                                                                         [ 95%]
> tests/integration/test_target_bigquery.py::TestIntegration::test_reserved_word_table_name PASSED                                                                 [100%]
> ```

Thank you @edgarrmondragon!

**Comment by NiallRees** [comment]
Hey @Samira-El - would you be able to approve the workflows and merge this assuming all are passing?

**Comment by Samira-El** [comment]
@jmriego can you take a look at the new changes? I can merge if it looks good to you.

**Comment by NiallRees** [comment]
@jmriego just a bump on the above, would love to get this merged

**Comment by jmriego** [comment]
sorry! just seeing this. Looking at the code everything looks fine but if that's alright with you I'd like verifying that this is not breaking any of the pipelines we have running now.
Do you have any example of a Postgres or MySQL schema that would be impacted by this?

**Comment by NiallRees** [comment]
Please could you clarify what you mean by:
> Do you have any example of a Postgres or MySQL schema that would be impacted by this?

For most use-cases this support for repeated records is used by taps which pull from APIs with complex objects vs flat database tables.

@edgarrmondragon has written integration tests along with this PR to assert the new functionality and the existing tests are still running fine. I'm using this branch in production as well, and it works really well. By all means test it on your pipelines too! :)

**Comment by jmriego** [comment]
@NiallRees an example of what I had in mind was what it's called composite types in Postgres: https://www.postgresql.org/docs/9.6/rowtypes.html
You can find similar things in BigQuery, Snowflake, etc. I was just worried this could potentially impact replication of non-API complex types.

After some testing I haven't seen any errors like that. It seems like this code still imports everything including arrays of composites as strings though. I'm fine with that abut it might make sense to rethink this in the future and see what's best for database use cases.

I'd say code looks good, there's proper testing and everything so this looks good to merge to me!

**Comment by edgarrmondragon** [comment]
@jmriego thanks for your comments!

> It seems like this code still imports everything including arrays of composites as strings though. I'm fine with that abut it might make sense to rethink this in the future and see what's best for database use cases.

AFAIK composite types generally don't have good support in Singer taps, so I wonder what JSON schema they discover for such columns.

For example, the following table with an array of composites

```sql
CREATE TYPE inventory_item AS (
     name            text,
     supplier_id     integer,
     price           numeric
 );

CREATE TABLE array_comp (items inventory_item[]);

INSERT INTO array_comp VALUES
(ARRAY[ROW('fuzzy dice', 42, 1.99)::inventory_item, ROW('test', 43, 4.99)::inventory_item]);
```

extracted with [pipelinewise-tap-postgres](https://github.com/transferwise/pipelinewise-tap-postgres) produces this record message

```json
{
  "type": "RECORD",
  "stream": "public-array_comp",
  "record": {
    "items": [
      "{",
      "\"",
      "(",
      "\\",
      "\"",
      "f",
      "u",
      "z",
      "z",
      "y",
      " ",
      "d",
      "i",
      "c",
      "e",
      "\\",
      "\"",
      ",",
      "4",
      "2",
      ",",
      "1",
      ".",
      "9",
      "9",
      ")",
      "\"",
      ",",
      "\"",
      "(",
      "t",
      "e",
      "s",
      "t",
      ",",
      "4",
      "3",
      ",",
      "4",
      ".",
      "9",
      "9",
      ")",
      "\"",
      "}"
    ]
  },
  "version": 1639944324439,
  "time_extracted": "2021-12-19T20:05:24.439533Z"
}
```

and this schema message

```json
{
  "type": "SCHEMA",
  "stream": "public-array_comp",
  "schema": {
    "type": "object",
    "properties": {
      "items": {
        "type": [
          "null",
          "array"
        ],
        "items": {
          "$ref": "#/definitions/sdc_recursive_string_array"
        }
      }
    },
    "definitions": {
      "sdc_recursive_integer_array": {
        "type": [
          "null",
          "integer",
          "array"
        ],
        "items": {
          "$ref": "#/definitions/sdc_recursive_integer_array"
        }
      },
      "sdc_recursive_number_array": {
        "type": [
          "null",
          "number",
          "array"
        ],
        "items": {
          "$ref": "#/definitions/sdc_recursive_number_array"
        }
      },
      "sdc_recursive_string_array": {
        "type": [
          "null",
          "string",
          "array"
        ],
        "items": {
          "$ref": "#/definitions/sdc_recursive_string_array"
        }
      },
      "sdc_recursive_boolean_array": {
        "type": [
          "null",
          "boolean",
          "array"
        ],
        "items": {
          "$ref": "#/definitions/sdc_recursive_boolean_array"
        }
      },
      "sdc_recursive_timestamp_array": {
        "type": [
          "null",
          "string",
          "array"
        ],
        "format": "date-time",
        "items": {
          "$ref": "#/definitions/sdc_recursive_timestamp_array"
        }
      },
      "sdc_recursive_object_array": {
        "type": [
          "null",
          "object",
          "array"
        ],
        "items": {
          "$ref": "#/definitions/sdc_recursive_object_array"
        }
      }
    }
  },
  "key_properties": [],
  "bookmark_properties": []
}
```

**Comment by jmriego** [comment]
thanks for checking that @edgarrmondragon. That's interesting, I didn't expect the issue would be on the tap. Good catch!

For me this is even more reason to be able to merge this for now as not even the taps generate the expected format that would allow for nested fields. It's very possible, once they solve that, that this MR will actually process them correctly

**Review by Samira-El — APPROVED** [review]

**Comment by Samira-El** [comment]
New release:
https://pypi.org/project/pipelinewise-target-bigquery/1.2.0/

**Comment by edgarrmondragon** [comment]
Thank you @Samira-El!

**Pull request merged**
