### PR TITLE
Hard delete mapping

### PR DESCRIPTION
**Pull request by judahrand**
## Problem

Sometimes one wants to `hard_delete` records from some tables but not others. This might be the case if some tables contain user related data but others do not.

## Proposed changes

Add a config option to enable `hard_delete` on some streams but not others.

## Types of changes

What types of changes does your code introduce to target-bigquery?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Description above provides context of the change
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [x] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [x] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [x] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by judahrand** [comment]
@Samira-El This might also be useful for `target-snowflake`?

**Comment by judahrand** [comment]
@Samira-El See https://github.com/thread/pipelinewise-target-bigquery for the running integration tests.

**Review by Samira-El — APPROVED** [review]
lgtm

**Comment by judahrand** [comment]
@Samira-El Is there anything blocking this?

**Pull request merged**
