### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by jmriego**
## Context

The README was not up to date in its configuration keys as mentioned in #21 

### Changes

Review all config keys and update the README with same explanation for them as the Snowflake target

## Checklist
- [x] I have considered the impact of this change and added a [Change Classification](
https://transferwise.atlassian.net/wiki/spaces/EKB/pages/1401189673/Change+Classifications+and+Expectations) Label (`change:standard`, `change:impactful`, `change:emergency`)
- [x] Change meets or does not compromise the [Baseline Security Requirements](https://transferwise.atlassian.net/wiki/spaces/EKB/pages/434929973/Baseline+Security+Requirements)

### CODE REVIEW

**Comment by jmriego** [comment]
@koszti I have this merge request and another one sent here (for updating the Google lib). There might be a conflict in the CHANGELOG so let me know if you want me to add those two things here instead and close the other MR

**Review by koszti — APPROVED** [review]

**Comment by koszti** [comment]
@jmriego, I removed the CHANGELOG from this PR and merged it. Normally we update the changelog only when we bump the version and publish new version to pypi.

If you think it's a good time for a new version then can you please send a PR, bump the version in `setup.py` and add list of changes in README. We're trying to use semantic versioning, so bump major in case of breaking changes, bump minor in case of new features and bump patch in case of bugfix. 🙇

**Comment by jmriego** [comment]
thanks @koszti !
Sure, that makes sense. I think for now it's fine as it's only a dependency update and fixing the README which I don't think would really be that interesting in PyPi. As soon as there's some other change needed I'll update the version if that's ok

**Comment by socketbox** [comment]
Sorry for the belated response. Thank you very much for doing this.

**Pull request merged**
