### PR TITLE
Support existing table partitions 

### LINKED ISSUE #88: BigQuery merges can be very expensive
BigQuery merges can be extremely expensive on large tables. I suggest adding the optional behavior which replicates what DBT's dynamic `insert_overwrite` strategy does as documented here: https://discourse.getdbt.com/t/bigquery-dbt-incremental-changes/982

The `partition_by` dictionary could be stored in the state file and written by PipelineWise FastSync like the `replication_method` and `replication_key` entries are currently.

### PR DESCRIPTION
**Pull request by judahrand**
## Problem

Fixes #88 

## Types of changes

What types of changes does your code introduce to target-bigquery?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] Description above provides context of the change
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by judahrand** [comment]
@jmriego Would you be happy with this implementation and testing? On the testing front this is the same level of testing as currently exists for current behaviour afaik.

**Comment by jmriego** [comment]
sorry for the delay, I'm still trying to grasp all the changes here. I'll try adding some comments with the things I'm finding harder to figure out.
Do you mind adding some comments? This is quite a big MR and I can see things here related to partitioning, clustering (which I thought was in #87 instead) and some code changes which I understand is for making code clearer?

**Comment by jmriego** [comment]
I'm thinking about refactoring some of the code as I'm starting to understand why you had to introduce certain changes. It might be better if we leave this type of refactoring for a separate MR which I'm happy to work on myself. I'm going to start on that and will have the changes in a day or two

**Comment by jmriego** [comment]
I have made quite a few changes to the repo and this would need some refactoring. I didn't add this to the repo yet because I'm finding here code for clustering (which is on the other MR) and some other changes that are not required.
Also during testing I noticed this wouldn't work in a case like this (like what we discussed in #88):
| id | name | modified_date |
| 1 | Joe | 2021-01-01 |

Then we get a new value like this:
| id | name | modified_date |
| 1 | David | 2021-02-01 |

Like what you were saying, this would introduce duplicates in its current state. In my opinion we should instead only filter by partitions if they are part of the primary key. In the meantime I'm going to add an append_only option to this target as that's an easier way to reduce costs if people want to do the merge separately later

**Pull request closed without merging**
