### PR TITLE
Add `batch_wait_limit_seconds`

### PR DESCRIPTION
**Pull request by judahrand**
## Problem

This Pull Request addresses the same problem as https://github.com/transferwise/pipelinewise-target-snowflake/pull/164 but for this target.

## Proposed changes

This Pull Request is directly based on the changes made here: https://github.com/transferwise/pipelinewise-target-snowflake/pull/164

## Types of changes

What types of changes does your code introduce to target-bigquery?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Description above provides context of the change
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Unit tests for changes (not needed for documentation changes)
- [x] CI checks pass with my changes
- [x] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [x] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [x] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by judahrand** [comment]
@Samira-El This seems like a PR for you since you gave the review on the PR that this is based on?

**Comment by judahrand** [comment]
@Samira-El Please can you or someone review this?

**Comment by judahrand** [comment]
@Samira-El bump

**Review by Samira-El — COMMENTED** [review]
Lgtm, please note tho that this time base flushing only kinda make sense when you have `flush_all_streams` set to true.

**Comment by judahrand** [comment]
> Lgtm, please note tho that this time base flushing only kinda make sense when you have `flush_all_streams` set to true.

@Samira-El I see what you mean. I've reworked this slightly to make it at least make sense without `flush_all_steams` set to true. What do you think of this slightly altered approach?

With these changes whenever a message is received for any stream it will trigger a check as to whether or not streams should be flushed independently based on the last time they were flushed.

**Comment by judahrand** [comment]
@Samira-El See https://github.com/thread/pipelinewise-target-bigquery for the running integration tests.

**Comment by judahrand** [comment]
@Samira-El  Is there anything blocking this?

**Comment by jmriego** [comment]
Sorry, we're in the process of migrating the ownership of this repo. As soon as I become the owner of the repo I'll set up BigQuery to be tested on the ci/cd pipeline for the integration tests. I can tell you that the code looks good and it shouldn't take long to set it all up

**Comment by judahrand** [comment]
> 

We've also got the tests running on our fork if that helps 😊

https://github.com/thread/pipelinewise-target-bigquery/pull/1

**Comment by jmriego** [comment]
thanks for the merge request @judahrand ! Can you rebase this so there is no conflicts? I already got CI working so we are good to go here :)

**Comment by judahrand** [comment]
@jmriego Rebased

**Pull request merged**
