### PR TITLE
Remove joblib dependency

### PR DESCRIPTION
**Pull request by judahrand**
## Problem

Given that no Numpy arrays or complex types are used I don't think there is any reason to use `joblib` rather than the standard library for concurrency. This allows us to remove a dependency.

## Proposed changes

Use the standard library and remove `joblib` from dependencies.

## Types of changes

What types of changes does your code introduce to target-bigquery?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Description above provides context of the change
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [x] CI checks pass with my changes
- [x] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [x] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [x] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by judahrand** [comment]
@jmriego Is there anything blocking this?

**Comment by judahrand** [comment]
@jmriego Rebased

**Comment by judahrand** [comment]
@jmriego Conflicts resolved.

**Comment by jmriego** [comment]
it's strange, this keeps on failing on the mapping with hard delete test

**Comment by judahrand** [comment]
I see the issue. It was a bug introduced when I rebased. Will fix now.

**Comment by judahrand** [comment]
Done.

**Comment by judahrand** [comment]
Sorry about this. As I say it is working on our fork so must have messed up the rebase still...

**Comment by judahrand** [comment]
@jmriego Okay, actually fixed it this time.

**Comment by jmriego** [comment]
no worries! at least this is proving that the CI/CD testing is working as expected and you added good tests :)

**Pull request merged**
